version: "3.3"

volumes:
  tailscale-data:
    driver: local

services:
  tailscale:
    image: tailscale/tailscale:stable
    hostname: tailscale
    env_file:
      - ./tailscale/.env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--accept-routes
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    restart: always
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Asia/Tokyo"
      SERVERURL: syoch.f5.si
      SERVERPORT: 53
      PEERS: syocharch,openwrt  # Peer名 (それぞれ鍵が発行される)

    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    ports:
      - 53:51820/udp
